version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
      - proxy

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - ./ELK/config/logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
      - proxy

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - elasticsearch  
    networks:
      - elk
      - proxy
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.kibana.rule=Host(`kibana.elk.be`)"
    #   - "traefik.http.routers.kibana.entrypoints=web"
    #   - "traefik.http.services.kibana.loadbalancer.server.port=5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    restart: always
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./ELK/config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - logstash
    networks:
      - elk
      - proxy


volumes:
  elastic_data: {}

networks:
  elk:
  proxy:
    external: true
    name: traefik
